# Generated by Django 3.1 on 2020-08-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('out_name1', models.CharField(blank=True, max_length=128, null=True)),
                ('out_name2', models.CharField(blank=True, max_length=128, null=True)),
                ('out_name3', models.CharField(blank=True, max_length=128, null=True)),
                ('out_name4', models.CharField(blank=True, max_length=128, null=True)),
                ('out_name5', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
